//! Merger module for combining split SQL files back into a single dump.

use crate::parser::SqlDialect;
use crate::transform_common::{write_dialect_footer, write_dialect_header};
use std::collections::HashSet;
use std::fs::{self, File};
use std::io::{self, BufWriter, Read, Write};
use std::path::{Path, PathBuf};

/// Statistics from merge operation
#[derive(Debug, Default, serde::Serialize)]
pub struct MergeStats {
    /// Number of tables merged.
    pub tables_merged: usize,
    /// Total bytes written to output.
    pub bytes_written: u64,
    /// Names of tables that were merged.
    pub table_names: Vec<String>,
}

/// Merger configuration
#[derive(Default)]
pub struct MergerConfig {
    pub dialect: SqlDialect,
    pub tables: Option<HashSet<String>>,
    pub exclude: HashSet<String>,
    pub add_transaction: bool,
    pub add_header: bool,
}

/// Called after each input file with `(input bytes processed, total input bytes)`.
pub type ProgressFn = Box<dyn Fn(u64, u64)>;

/// Merger for combining split SQL files
pub struct Merger {
    input_dir: PathBuf,
    output: Option<PathBuf>,
    config: MergerConfig,
    progress: Option<ProgressFn>,
}

impl Merger {
    pub fn new(input_dir: PathBuf, output: Option<PathBuf>) -> Self {
        Self {
            input_dir,
            output,
            config: MergerConfig::default(),
            progress: None,
        }
    }

    pub fn with_dialect(mut self, dialect: SqlDialect) -> Self {
        self.config.dialect = dialect;
        self
    }

    pub fn with_tables(mut self, tables: HashSet<String>) -> Self {
        self.config.tables = Some(tables);
        self
    }

    pub fn with_exclude(mut self, exclude: HashSet<String>) -> Self {
        self.config.exclude = exclude;
        self
    }

    pub fn with_transaction(mut self, add_transaction: bool) -> Self {
        self.config.add_transaction = add_transaction;
        self
    }

    pub fn with_header(mut self, add_header: bool) -> Self {
        self.config.add_header = add_header;
        self
    }

    pub fn with_progress(mut self, progress: ProgressFn) -> Self {
        self.progress = Some(progress);
        self
    }

    /// Discover, filter and sort the `.sql` files that `merge` would combine.
    pub fn plan(&self) -> anyhow::Result<Vec<(String, PathBuf)>> {
        let sql_files = discover_sql_files(&self.input_dir)?;
        if sql_files.is_empty() {
            anyhow::bail!(
                "no .sql files found in directory: {}",
                self.input_dir.display()
            );
        }

        let mut files: Vec<(String, PathBuf)> = sql_files
            .into_iter()
            .filter(|(name, _)| {
                let name_lower = name.to_lowercase();
                if let Some(ref include) = self.config.tables {
                    if !include.contains(&name_lower) {
                        return false;
                    }
                }
                !self.config.exclude.contains(&name_lower)
            })
            .collect();

        if files.is_empty() {
            anyhow::bail!("no tables remaining after filtering");
        }

        files.sort_by(|a, b| a.0.cmp(&b.0));
        Ok(files)
    }

    /// Run the merge operation
    pub fn merge(&self) -> anyhow::Result<MergeStats> {
        let files = self.plan()?;

        if let Some(ref out_path) = self.output {
            if let Some(parent) = out_path.parent() {
                fs::create_dir_all(parent)?;
            }
            let file = File::create(out_path)?;
            self.merge_files(files, BufWriter::with_capacity(256 * 1024, file))
        } else {
            let stdout = io::stdout();
            self.merge_files(files, BufWriter::new(stdout.lock()))
        }
    }

    fn merge_files<W: Write>(
        &self,
        files: Vec<(String, PathBuf)>,
        writer: W,
    ) -> anyhow::Result<MergeStats> {
        let mut stats = MergeStats::default();
        let mut writer = CountingWriter {
            inner: writer,
            bytes: 0,
        };
        let dialect = self.config.dialect;

        let total_input: u64 = files
            .iter()
            .map(|(_, p)| fs::metadata(p).map(|m| m.len()).unwrap_or(0))
            .sum();
        let mut input_done: u64 = 0;

        if self.config.add_header {
            writeln!(writer, "-- SQL Merge Output")?;
            writeln!(writer, "-- Generated by sql-splitter")?;
            writeln!(writer, "-- Tables: {}", files.len())?;
            writeln!(writer, "-- Dialect: {}", dialect)?;
            writeln!(writer)?;
            write_dialect_header(&mut writer, dialect)?;
        }

        if self.config.add_transaction {
            let tx_start = match dialect {
                SqlDialect::MySql => "START TRANSACTION;\n\n",
                SqlDialect::Postgres => "BEGIN;\n\n",
                SqlDialect::Sqlite | SqlDialect::Mssql => "BEGIN TRANSACTION;\n\n",
            };
            writer.write_all(tx_start.as_bytes())?;
        }

        let mut buf = vec![0u8; 64 * 1024];
        for (table_name, path) in &files {
            write!(
                writer,
                "\n-- ============================================================\n-- Table: {}\n-- ============================================================\n\n",
                table_name
            )?;

            // Stream file content as raw bytes (byte-exact, no per-line
            // allocation, and non-UTF-8 data passes through untouched)
            let mut file = File::open(path)?;
            let mut last_byte = b'\n';
            loop {
                let n = file.read(&mut buf)?;
                if n == 0 {
                    break;
                }
                writer.write_all(&buf[..n])?;
                last_byte = buf[n - 1];
                input_done += n as u64;
            }

            // Ensure statements from consecutive files stay separated
            if last_byte != b'\n' {
                writer.write_all(b"\n")?;
            }

            if let Some(progress) = &self.progress {
                progress(input_done, total_input);
            }
            stats.table_names.push(table_name.clone());
            stats.tables_merged += 1;
        }

        if self.config.add_transaction {
            writer.write_all(b"\nCOMMIT;\n")?;
        }

        if self.config.add_header {
            write_dialect_footer(&mut writer, dialect)?;
        }

        writer.flush()?;
        stats.bytes_written = writer.bytes;
        Ok(stats)
    }
}

/// Discover all .sql files in a directory, returning (table_name, path) pairs
pub fn discover_sql_files(dir: &Path) -> anyhow::Result<Vec<(String, PathBuf)>> {
    let mut files = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        let is_sql = path
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("sql"));
        if path.is_file() && is_sql {
            if let Some(stem) = path.file_stem() {
                files.push((stem.to_string_lossy().to_string(), path));
            }
        }
    }
    Ok(files)
}

struct CountingWriter<W> {
    inner: W,
    bytes: u64,
}

impl<W: Write> Write for CountingWriter<W> {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        let n = self.inner.write(buf)?;
        self.bytes += n as u64;
        Ok(n)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}
