version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: sql-splitter
    main: .
    binary: sql-splitter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/helgesverre/sql-splitter/cmd.Version={{.Version}}
      - -X github.com/helgesverre/sql-splitter/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/helgesverre/sql-splitter/cmd.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: helgesverre
    name: sql-splitter
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
