//! Exact-output tests for the differ SQL and text formatters.
//!
//! Every test builds a `DiffResult` by hand and pins the emitted lines so a
//! change in quoting, keyword choice, or dialect branching fails loudly.

use sql_splitter::differ::{
    format_diff, ColumnChange, ColumnInfo, DataDiff, DiffOutputFormat, DiffResult, DiffSummary,
    FkInfo, IndexInfo, SchemaDiff, TableDataDiff, TableInfo, TableModification,
};
use sql_splitter::parser::SqlDialect;
use std::collections::HashMap;

const ALL: [SqlDialect; 4] = [
    SqlDialect::MySql,
    SqlDialect::Postgres,
    SqlDialect::Sqlite,
    SqlDialect::Mssql,
];

fn summary() -> DiffSummary {
    DiffSummary {
        tables_added: 0,
        tables_removed: 0,
        tables_modified: 0,
        rows_added: 0,
        rows_removed: 0,
        rows_modified: 0,
        truncated: false,
    }
}

fn result(schema: Option<SchemaDiff>, data: Option<DataDiff>) -> DiffResult {
    DiffResult {
        schema,
        data,
        warnings: vec![],
        summary: summary(),
    }
}

fn schema_with(m: TableModification) -> DiffResult {
    result(
        Some(SchemaDiff {
            tables_added: vec![],
            tables_removed: vec![],
            tables_modified: vec![m],
        }),
        None,
    )
}

fn modification(table: &str) -> TableModification {
    TableModification {
        table_name: table.to_string(),
        columns_added: vec![],
        columns_removed: vec![],
        columns_modified: vec![],
        pk_changed: false,
        old_pk: None,
        new_pk: None,
        fks_added: vec![],
        fks_removed: vec![],
        indexes_added: vec![],
        indexes_removed: vec![],
    }
}

fn col(name: &str, ty: &str, nullable: bool) -> ColumnInfo {
    ColumnInfo {
        name: name.to_string(),
        col_type: ty.to_string(),
        is_nullable: nullable,
        is_primary_key: false,
    }
}

fn strs(v: &[&str]) -> Vec<String> {
    v.iter().map(|s| s.to_string()).collect()
}

fn sql(r: &DiffResult, d: SqlDialect) -> String {
    format_diff(r, DiffOutputFormat::Sql, d)
}

fn text(r: &DiffResult) -> String {
    format_diff(r, DiffOutputFormat::Text, SqlDialect::MySql)
}

/// Quote `name` the way each dialect's formatter does.
fn q(d: SqlDialect, name: &str) -> String {
    match d {
        SqlDialect::MySql => format!("`{name}`"),
        SqlDialect::Postgres | SqlDialect::Sqlite => format!("\"{name}\""),
        SqlDialect::Mssql => format!("[{name}]"),
    }
}

fn assert_line(out: &str, line: &str) {
    assert!(
        out.lines().any(|l| l == line),
        "expected line {line:?} in output:\n{out}"
    );
}

// =============================================================================
// Header / empty cases
// =============================================================================

#[test]
fn sql_header_names_dialect() {
    let r = result(None, None);
    for d in ALL {
        let out = sql(&r, d);
        assert_eq!(
            out,
            format!(
                "-- SQL Migration Script\n-- Generated by sql-splitter diff (dialect: {d})\n--\n\n-- No schema changes detected\n"
            )
        );
    }
}

#[test]
fn sql_empty_schema_diff_reports_no_changes() {
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![],
            tables_removed: vec![],
            tables_modified: vec![],
        }),
        None,
    );
    let out = sql(&r, SqlDialect::Postgres);
    assert!(out.ends_with("-- No schema changes detected\n"));
    assert!(!out.contains("ALTER"));
}

#[test]
fn sql_skips_modification_without_changes() {
    // A TableModification with nothing set must not emit a header.
    let r = schema_with(modification("noop"));
    let out = sql(&r, SqlDialect::MySql);
    assert!(!out.contains("Modified table: noop"), "{out}");
}

// =============================================================================
// Tables added / removed
// =============================================================================

#[test]
fn sql_added_table_uses_create_statement_and_appends_semicolon() {
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![TableInfo {
                name: "t".into(),
                columns: vec![],
                primary_key: vec![],
                create_statement: Some("  CREATE TABLE t (id INT)  ".into()),
            }],
            tables_removed: vec![],
            tables_modified: vec![],
        }),
        None,
    );
    let out = sql(&r, SqlDialect::MySql);
    assert!(
        out.contains("-- New table: t\nCREATE TABLE t (id INT);\n\n"),
        "{out}"
    );

    // Already-terminated statements are not double-terminated.
    let r2 = result(
        Some(SchemaDiff {
            tables_added: vec![TableInfo {
                name: "t".into(),
                columns: vec![],
                primary_key: vec![],
                create_statement: Some("CREATE TABLE t (id INT);".into()),
            }],
            tables_removed: vec![],
            tables_modified: vec![],
        }),
        None,
    );
    assert!(!sql(&r2, SqlDialect::MySql).contains(";;"));
}

#[test]
fn sql_added_table_synthesizes_create_from_columns() {
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![TableInfo {
                name: "orders".into(),
                columns: vec![col("id", "INT", false), col("note", "TEXT", true)],
                primary_key: strs(&["id"]),
                create_statement: None,
            }],
            tables_removed: vec![],
            tables_modified: vec![],
        }),
        None,
    );
    for d in ALL {
        let out = sql(&r, d);
        let expected = format!(
            "-- New table: orders\nCREATE TABLE {} (\n  {} INT NOT NULL,\n  {} TEXT,\n  PRIMARY KEY ({})\n);\n\n",
            q(d, "orders"),
            q(d, "id"),
            q(d, "note"),
            q(d, "id")
        );
        assert!(out.contains(&expected), "dialect {d}:\n{out}");
    }
}

#[test]
fn sql_added_table_without_pk_has_no_pk_clause() {
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![TableInfo {
                name: "logs".into(),
                columns: vec![col("msg", "TEXT", true)],
                primary_key: vec![],
                create_statement: None,
            }],
            tables_removed: vec![],
            tables_modified: vec![],
        }),
        None,
    );
    let out = sql(&r, SqlDialect::Sqlite);
    assert!(
        out.contains("CREATE TABLE \"logs\" (\n  \"msg\" TEXT\n);\n"),
        "{out}"
    );
    assert!(!out.contains("PRIMARY KEY"));
}

#[test]
fn sql_removed_table_per_dialect() {
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![],
            tables_removed: strs(&["old"]),
            tables_modified: vec![],
        }),
        None,
    );
    for d in ALL {
        let out = sql(&r, d);
        assert_line(&out, "-- Removed table: old");
        assert_line(&out, &format!("DROP TABLE IF EXISTS {};", q(d, "old")));
    }
}

// =============================================================================
// Column changes
// =============================================================================

#[test]
fn sql_add_and_drop_column_per_dialect() {
    let mut m = modification("users");
    m.columns_added = vec![
        col("email", "VARCHAR(255)", false),
        col("bio", "TEXT", true),
    ];
    m.columns_removed = vec![col("legacy", "INT", true)];
    let r = schema_with(m);
    for d in ALL {
        let out = sql(&r, d);
        let t = q(d, "users");
        assert_line(&out, "-- Modified table: users");
        assert_line(
            &out,
            &format!(
                "ALTER TABLE {t} ADD COLUMN {} VARCHAR(255) NOT NULL;",
                q(d, "email")
            ),
        );
        assert_line(
            &out,
            &format!("ALTER TABLE {t} ADD COLUMN {} TEXT;", q(d, "bio")),
        );
        assert_line(
            &out,
            &format!("ALTER TABLE {t} DROP COLUMN {};", q(d, "legacy")),
        );
    }
}

#[test]
fn sql_modify_column_mysql_uses_modify_column() {
    let mut m = modification("users");
    m.columns_modified = vec![ColumnChange {
        name: "age".into(),
        old_type: Some("INT".into()),
        new_type: Some("BIGINT".into()),
        old_nullable: Some(true),
        new_nullable: Some(false),
    }];
    let out = sql(&schema_with(m), SqlDialect::MySql);
    assert_line(
        &out,
        "ALTER TABLE `users` MODIFY COLUMN `age` BIGINT NOT NULL;",
    );
}

#[test]
fn sql_modify_column_mssql_uses_alter_column() {
    let mut m = modification("users");
    m.columns_modified = vec![ColumnChange {
        name: "age".into(),
        old_type: Some("INT".into()),
        new_type: Some("BIGINT".into()),
        old_nullable: None,
        new_nullable: None,
    }];
    let out = sql(&schema_with(m), SqlDialect::Mssql);
    assert_line(&out, "ALTER TABLE [users] ALTER COLUMN [age] BIGINT;");
}

#[test]
fn sql_modify_column_postgres_splits_type_and_nullability() {
    let mut m = modification("users");
    m.columns_modified = vec![
        ColumnChange {
            name: "age".into(),
            old_type: Some("INT".into()),
            new_type: Some("BIGINT".into()),
            old_nullable: Some(true),
            new_nullable: Some(false),
        },
        ColumnChange {
            name: "nick".into(),
            old_type: None,
            new_type: None,
            old_nullable: Some(false),
            new_nullable: Some(true),
        },
    ];
    let out = sql(&schema_with(m), SqlDialect::Postgres);
    assert_line(
        &out,
        "ALTER TABLE \"users\" ALTER COLUMN \"age\" TYPE BIGINT;",
    );
    assert_line(
        &out,
        "ALTER TABLE \"users\" ALTER COLUMN \"age\" SET NOT NULL;",
    );
    assert_line(
        &out,
        "ALTER TABLE \"users\" ALTER COLUMN \"nick\" DROP NOT NULL;",
    );
    // Nullability-only change must not emit a TYPE statement.
    assert!(!out.contains("\"nick\" TYPE"), "{out}");
}

#[test]
fn sql_modify_column_without_type_uses_placeholder() {
    let mut m = modification("users");
    m.columns_modified = vec![ColumnChange {
        name: "nick".into(),
        old_type: None,
        new_type: None,
        old_nullable: Some(false),
        new_nullable: Some(true),
    }];
    let out = sql(&schema_with(m), SqlDialect::MySql);
    assert_line(
        &out,
        "ALTER TABLE `users` MODIFY COLUMN `nick` -- unknown type;",
    );
}

#[test]
fn sql_modify_column_sqlite_is_comment_only() {
    let mut m = modification("users");
    m.columns_modified = vec![ColumnChange {
        name: "age".into(),
        old_type: Some("INT".into()),
        new_type: Some("BIGINT".into()),
        old_nullable: None,
        new_nullable: None,
    }];
    let out = sql(&schema_with(m), SqlDialect::Sqlite);
    assert_line(
        &out,
        "-- SQLite does not support ALTER COLUMN; manual migration required for users.age",
    );
    assert!(!out.contains("ALTER COLUMN \"age\""), "{out}");
}

// =============================================================================
// Foreign keys
// =============================================================================

fn fk(name: Option<&str>) -> FkInfo {
    FkInfo {
        name: name.map(String::from),
        columns: strs(&["a", "b"]),
        referenced_table: "parent".into(),
        referenced_columns: strs(&["x", "y"]),
    }
}

#[test]
fn sql_add_fk_named_and_unnamed_per_dialect() {
    let mut m = modification("child");
    m.fks_added = vec![fk(Some("fk_child")), fk(None)];
    let r = schema_with(m);
    for d in ALL {
        let out = sql(&r, d);
        let cols = format!("{}, {}", q(d, "a"), q(d, "b"));
        let refs = format!("{}, {}", q(d, "x"), q(d, "y"));
        assert_line(
            &out,
            &format!(
                "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({cols}) REFERENCES {}({refs});",
                q(d, "child"),
                q(d, "fk_child"),
                q(d, "parent")
            ),
        );
        assert_line(
            &out,
            &format!(
                "ALTER TABLE {} ADD FOREIGN KEY ({cols}) REFERENCES {}({refs});",
                q(d, "child"),
                q(d, "parent")
            ),
        );
    }
}

#[test]
fn sql_drop_named_fk_per_dialect() {
    let mut m = modification("child");
    m.fks_removed = vec![fk(Some("fk_child"))];
    let r = schema_with(m);
    assert_line(
        &sql(&r, SqlDialect::MySql),
        "ALTER TABLE `child` DROP FOREIGN KEY `fk_child`;",
    );
    assert_line(
        &sql(&r, SqlDialect::Postgres),
        "ALTER TABLE \"child\" DROP CONSTRAINT \"fk_child\";",
    );
    assert_line(
        &sql(&r, SqlDialect::Mssql),
        "ALTER TABLE [child] DROP CONSTRAINT [fk_child];",
    );
    assert_line(
        &sql(&r, SqlDialect::Sqlite),
        "-- SQLite does not support DROP CONSTRAINT; manual migration required for FK fk_child",
    );
}

#[test]
fn sql_drop_unnamed_fk_is_comment() {
    let mut m = modification("child");
    m.fks_removed = vec![fk(None)];
    let r = schema_with(m);
    for d in ALL {
        let out = sql(&r, d);
        assert_line(
            &out,
            "-- Cannot drop unnamed FK (a, b) -> parent.(x, y) without constraint name",
        );
        assert!(!out.contains("DROP CONSTRAINT"), "{d}: {out}");
        assert!(!out.contains("DROP FOREIGN KEY"), "{d}: {out}");
    }
}

// =============================================================================
// Indexes
// =============================================================================

fn idx(name: &str, unique: bool, ty: Option<&str>) -> IndexInfo {
    IndexInfo {
        name: name.into(),
        columns: strs(&["c1", "c2"]),
        is_unique: unique,
        index_type: ty.map(String::from),
    }
}

#[test]
fn sql_create_index_per_dialect() {
    let mut m = modification("t");
    m.indexes_added = vec![
        idx("ix_plain", false, None),
        idx("ix_uniq", true, Some("BTREE")),
    ];
    let r = schema_with(m);
    for d in ALL {
        let out = sql(&r, d);
        let cols = format!("{}, {}", q(d, "c1"), q(d, "c2"));
        // Only Postgres emits USING; other dialects ignore index_type.
        let using = if d == SqlDialect::Postgres {
            " USING btree"
        } else {
            ""
        };
        assert_line(
            &out,
            &format!(
                "CREATE INDEX {} ON {}({cols});",
                q(d, "ix_plain"),
                q(d, "t")
            ),
        );
        assert_line(
            &out,
            &format!(
                "CREATE UNIQUE INDEX {} ON {}{using}({cols});",
                q(d, "ix_uniq"),
                q(d, "t")
            ),
        );
    }
}

#[test]
fn sql_drop_index_per_dialect() {
    let mut m = modification("t");
    m.indexes_removed = vec![idx("ix_old", false, None)];
    let r = schema_with(m);
    assert_line(&sql(&r, SqlDialect::MySql), "DROP INDEX `ix_old` ON `t`;");
    assert_line(&sql(&r, SqlDialect::Mssql), "DROP INDEX [ix_old] ON [t];");
    assert_line(
        &sql(&r, SqlDialect::Postgres),
        "DROP INDEX IF EXISTS \"ix_old\";",
    );
    assert_line(
        &sql(&r, SqlDialect::Sqlite),
        "DROP INDEX IF EXISTS \"ix_old\";",
    );
}

// =============================================================================
// Primary key changes
// =============================================================================

fn pk_change(old: Option<&[&str]>, new: Option<&[&str]>) -> DiffResult {
    let mut m = modification("t");
    m.pk_changed = true;
    m.old_pk = old.map(strs);
    m.new_pk = new.map(strs);
    schema_with(m)
}

#[test]
fn sql_pk_change_mysql() {
    let out = sql(
        &pk_change(Some(&["id"]), Some(&["a", "b"])),
        SqlDialect::MySql,
    );
    assert_line(
        &out,
        "-- WARNING: PRIMARY KEY change (id) -> (a, b) may require table recreation",
    );
    assert_line(&out, "ALTER TABLE `t` DROP PRIMARY KEY;");
    assert_line(&out, "ALTER TABLE `t` ADD PRIMARY KEY (`a`, `b`);");
}

#[test]
fn sql_pk_change_postgres_and_mssql_drop_named_constraint() {
    let r = pk_change(Some(&["id"]), Some(&["uuid"]));
    let pg = sql(&r, SqlDialect::Postgres);
    assert_line(&pg, "ALTER TABLE \"t\" DROP CONSTRAINT IF EXISTS t_pkey;");
    assert_line(&pg, "ALTER TABLE \"t\" ADD PRIMARY KEY (\"uuid\");");

    let ms = sql(&r, SqlDialect::Mssql);
    assert_line(&ms, "ALTER TABLE [t] DROP CONSTRAINT IF EXISTS t_pkey;");
    assert_line(&ms, "ALTER TABLE [t] ADD PRIMARY KEY ([uuid]);");
}

#[test]
fn sql_pk_change_sqlite_skips_ddl() {
    let out = sql(
        &pk_change(Some(&["id"]), Some(&["uuid"])),
        SqlDialect::Sqlite,
    );
    assert_line(
        &out,
        "-- SQLite does not support ALTER PRIMARY KEY; table recreation required",
    );
    assert!(!out.contains("ADD PRIMARY KEY"), "{out}");
    assert!(!out.contains("DROP PRIMARY KEY"), "{out}");
}

#[test]
fn sql_pk_removed_only_drops() {
    // new_pk None -> "(none)" and no ADD PRIMARY KEY.
    let out = sql(&pk_change(Some(&["id"]), None), SqlDialect::MySql);
    assert_line(
        &out,
        "-- WARNING: PRIMARY KEY change (id) -> ((none)) may require table recreation",
    );
    assert_line(&out, "ALTER TABLE `t` DROP PRIMARY KEY;");
    assert!(!out.contains("ADD PRIMARY KEY"), "{out}");

    // Empty new_pk vec behaves the same as None for the ADD step.
    let out = sql(&pk_change(None, Some(&[])), SqlDialect::Postgres);
    assert_line(
        &out,
        "-- WARNING: PRIMARY KEY change ((none)) -> () may require table recreation",
    );
    assert!(!out.contains("ADD PRIMARY KEY"), "{out}");
}

#[test]
fn sql_pk_only_change_still_emits_table_header() {
    let out = sql(
        &pk_change(Some(&["id"]), Some(&["uuid"])),
        SqlDialect::MySql,
    );
    assert_line(&out, "-- Modified table: t");
}

// =============================================================================
// Data section
// =============================================================================

fn data(added: u64, removed: u64, modified: u64) -> DataDiff {
    let mut tables = HashMap::new();
    tables.insert(
        "users".to_string(),
        TableDataDiff {
            old_row_count: 5,
            new_row_count: 5,
            added_count: added,
            removed_count: removed,
            modified_count: modified,
            truncated: false,
            sample_added_pks: vec![],
            sample_removed_pks: vec![],
            sample_modified_pks: vec![],
        },
    );
    DataDiff { tables }
}

#[test]
fn sql_data_changes_noted_only_when_schema_changed() {
    let mut m = modification("t");
    m.columns_added = vec![col("x", "INT", true)];
    let schema = SchemaDiff {
        tables_added: vec![],
        tables_removed: vec![],
        tables_modified: vec![m],
    };

    let r = result(Some(schema), Some(data(1, 0, 0)));
    let out = sql(&r, SqlDialect::MySql);
    assert_line(
        &out,
        "-- Data changes detected but not included in migration script",
    );
    assert_line(
        &out,
        "-- Use text or JSON output format for data diff details",
    );

    // Zero-change data diff must not produce the note.
    let mut m2 = modification("t");
    m2.columns_added = vec![col("x", "INT", true)];
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![],
            tables_removed: vec![],
            tables_modified: vec![m2],
        }),
        Some(data(0, 0, 0)),
    );
    assert!(!sql(&r, SqlDialect::MySql).contains("Data changes detected"));

    // Data-only diff (no schema) short-circuits before the data note.
    let r = result(None, Some(data(1, 2, 3)));
    let out = sql(&r, SqlDialect::MySql);
    assert!(out.contains("No schema changes detected"));
    assert!(!out.contains("Data changes detected"), "{out}");
}

// =============================================================================
// Text formatter: index and sample lines
// =============================================================================

#[test]
fn text_index_lines_show_unique_and_type_markers() {
    let mut m = modification("t");
    m.indexes_added = vec![idx("ix_uniq", true, Some("BTREE"))];
    m.indexes_removed = vec![idx("ix_plain", false, None)];
    let out = text(&schema_with(m));
    assert_line(&out, "      + Index 'ix_uniq' on (c1, c2) [unique] [BTREE]");
    assert_line(&out, "      - Index 'ix_plain' on (c1, c2)");
}

#[test]
fn text_modified_column_and_pk_lines() {
    let mut m = modification("users");
    m.columns_added = vec![col("email", "TEXT", false)];
    m.columns_removed = vec![col("legacy", "INT", true)];
    m.columns_modified = vec![
        ColumnChange {
            name: "age".into(),
            old_type: Some("INT".into()),
            new_type: Some("BIGINT".into()),
            old_nullable: Some(true),
            new_nullable: Some(false),
        },
        ColumnChange {
            name: "nick".into(),
            old_type: None,
            new_type: None,
            old_nullable: Some(false),
            new_nullable: Some(true),
        },
    ];
    m.pk_changed = true;
    m.old_pk = Some(strs(&["id"]));
    m.new_pk = None;
    m.fks_added = vec![fk(Some("fk1"))];
    m.fks_removed = vec![fk(None)];
    let out = text(&schema_with(m));
    assert_line(&out, "  ~ Table 'users':");
    assert_line(&out, "      + Column 'email' TEXT NOT NULL");
    assert_line(&out, "      - Column 'legacy' INT");
    assert_line(&out, "      ~ Column 'age': INT → BIGINT, NULL → NOT NULL");
    assert_line(&out, "      ~ Column 'nick': NOT NULL → NULL");
    assert_line(&out, "      ~ PRIMARY KEY: (id) → ((none))");
    assert_line(&out, "      + FK (a, b) → parent.(x, y)");
    assert_line(&out, "      - FK (a, b) → parent.(x, y)");
}

#[test]
fn text_added_table_lists_columns_with_pk_marker() {
    let mut id = col("id", "INT", false);
    id.is_primary_key = true;
    let r = result(
        Some(SchemaDiff {
            tables_added: vec![TableInfo {
                name: "t".into(),
                columns: vec![id, col("name", "TEXT", true)],
                primary_key: strs(&["id"]),
                create_statement: None,
            }],
            tables_removed: strs(&["gone"]),
            tables_modified: vec![],
        }),
        None,
    );
    let out = text(&r);
    assert_line(&out, "  + Table 't' (new)");
    assert_line(&out, "      + id INT NOT NULL [PK]");
    assert_line(&out, "      + name TEXT NULL");
    assert_line(&out, "  - Table 'gone' (removed)");
}

#[test]
fn text_sample_lines_show_remaining_count_only_when_truncated() {
    let mut tables = HashMap::new();
    tables.insert(
        "users".to_string(),
        TableDataDiff {
            old_row_count: 5,
            new_row_count: 7,
            added_count: 3,
            removed_count: 2,
            modified_count: 1,
            truncated: false,
            sample_added_pks: strs(&["10", "11"]),
            sample_removed_pks: strs(&["(1, a)", "(2, b)"]),
            sample_modified_pks: vec![],
        },
    );
    let out = text(&result(None, Some(DataDiff { tables })));
    assert_line(&out, "  Table 'users': +3 rows, -2 rows, ~1 modified");
    assert_line(&out, "    Added PKs: 10, 11... (+1 more)");
    assert_line(&out, "    Removed PKs: (1, a), (2, b)");
    assert!(!out.contains("Modified PKs"), "{out}");
}

#[test]
fn text_skips_tables_without_changes_and_sorts_names() {
    let mut tables = HashMap::new();
    for (name, added) in [("zeta", 1), ("alpha", 2), ("quiet", 0)] {
        tables.insert(
            name.to_string(),
            TableDataDiff {
                old_row_count: 1,
                new_row_count: 1,
                added_count: added,
                ..Default::default()
            },
        );
    }
    let out = text(&result(None, Some(DataDiff { tables })));
    let a = out.find("Table 'alpha'").expect("alpha listed");
    let z = out.find("Table 'zeta'").expect("zeta listed");
    assert!(a < z, "tables must be sorted:\n{out}");
    assert!(!out.contains("quiet"), "{out}");
}

#[test]
fn text_empty_data_diff_says_no_changes() {
    let out = text(&result(
        None,
        Some(DataDiff {
            tables: HashMap::new(),
        }),
    ));
    assert_line(&out, "  (no data changes)");
}
