//! The credential guard: columns whose *name* marks them as secret material
//! (password, token, api key, secret, private key) are always generated by a
//! synthetic-only credential generator, no matter what values the dump held.
//!
//! This is deliberately high precedence — above every semantic-name and
//! observed-distribution heuristic — so a dump full of real password hashes or
//! live API keys can never round-trip into the emitted model as observed
//! samples. These candidates never carry source literals.

use super::{generator, Candidate, ColumnContext, Confidence, Precedence};
use crate::synthetic::model::GeneratorConfig;
use crate::synthetic::schema::SqlTypeFamily;

/// Propose the credential-guard candidate for a column, if its name looks like
/// secret material.
pub(super) fn candidates(ctx: &ColumnContext<'_>) -> Vec<Candidate> {
    let column = ctx.column();
    // Only text-shaped columns carry credential material we know how to
    // synthesize; a numeric "token_count" is not a token.
    if !matches!(
        column.family,
        SqlTypeFamily::Text | SqlTypeFamily::Other | SqlTypeFamily::Bytes
    ) {
        return Vec::new();
    }

    let Some((kind, confidence)) = classify(&column.name) else {
        return Vec::new();
    };

    vec![Candidate::new(
        Precedence::CredentialGuard,
        confidence,
        "credential_name_guard",
        credential_generator(kind),
    )]
}

/// Which credential generator a column name maps to, and how sure we are.
fn classify(name: &str) -> Option<(&'static str, Confidence)> {
    let lower = name.to_ascii_lowercase();

    // Password columns -> an unmistakably synthetic password hash.
    if contains_any(&lower, &["password", "passwd", "pwd", "password_hash"]) {
        return Some(("credential.password_hash", Confidence::High));
    }
    // Private keys / PEM material -> a fixed, invalid placeholder.
    if contains_any(&lower, &["private_key", "privatekey", "secret_key", "pem"]) {
        return Some(("credential.placeholder", Confidence::High));
    }
    // API keys.
    if contains_any(
        &lower,
        &["api_key", "apikey", "api_secret", "client_secret"],
    ) {
        return Some(("credential.api_key", Confidence::High));
    }
    // Bearer / session / refresh tokens.
    if contains_any(
        &lower,
        &[
            "access_token",
            "refresh_token",
            "session_token",
            "auth_token",
            "bearer",
            "token",
        ],
    ) {
        return Some(("credential.token", Confidence::High));
    }
    // Generic secrets and salts.
    if contains_any(&lower, &["secret", "salt"]) {
        return Some(("credential.secret", Confidence::Medium));
    }
    None
}

fn credential_generator(kind: &'static str) -> GeneratorConfig {
    generator(kind)
}

fn contains_any(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().any(|needle| haystack.contains(needle))
}
